# Generated by Django 3.2 on 2022-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personages', '0002_auto_20220503_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
